### ISSUE TITLE
Low-level policy training Data Preparation Bug

### ISSUE THREAD

**Issue by jackspp** [facebookresearch/latent-space-priors#2]
Thanks for publishing this nice work. I met some bug when creating 'lcs2-lo.h5' for training low-policy net. 
I sucecessfully finished vae training and prior training parts, however there seems like some bugs in `scripts/gen_amass_mjbox.py`:

1.  ```find <path-to-cmu-clips> -name '*_poses.npz' | PYTHONPATH=$PWD python scripts/gen_amass_mjbox.py -f - --subset cmu_locomotion_small --checkpoint vae/checkpoint.pt --output-path lcs2-lo.h5``` : maybe the checkpoint should be prior/checkpoint.pt ? 
2.  `zs` is not found in "*._posez.npz", seems like they are input for `prior`,   do it mean i need to convert lcs2-with-latents.h5` to new npz files ?

Thanks !

**Comment by jgehring** [comment]
Hi @jackspp, thanks for your interest in the repo! What's the error message you're seeing? Regarding your questions, maybe let me summarize how the training stages operate on the npz poses:

1. `scripts/gen_amass_jpos.py` extracts data for VAE training -- this will be just the pose data.

2. `scripts/add_latents_to_hdf5.py` adds VAE states to the training file above for subsequent prior (i.e., Transformer) training.

3. `scripts/gen_amass_mjbox.py` extracts data for low-level policy training, which is also pose data (although featurized differently, and hence the separate script) plus VAE states. It thus needs access to a VAE checkpoint, but the prior is not required here.

Steps 2 and 3 are independent of each other. Does this clarify things?

**Comment by jgehring** [comment]
Closing this for now, please let me know if you run into any issues!
